[project]
name = "mylib"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11, <3.14"
dependencies = [
    "opentelemetry-api>=1.0.0,<2.0.0",
    "opentelemetry-semantic-conventions>=0.65b0",
]

[project.optional-dependencies]
s3 = [
    "boto3>=1.43.89",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
