[project]
name = "gl-observability-sdk-cookbook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.14"
dependencies = [
    "gl-observability-binary[all]>=0.2.1",
    "opentelemetry-instrumentation-sqlite3>=0.62b1",
    "python-dotenv>=1.2.2",
    "uvicorn>=0.48.0",
]

[tool.uv.workspace]
members = [
    "traces/mylib",
]
